### ISSUE TITLE
I don't get any response by your app

### ISSUE THREAD

**Issue by TopicOffic** [ravenkls/MilkPlayer#1]
![Screenshot (245)](https://user-images.githubusercontent.com/48392397/69005303-a5979680-0920-11ea-962f-35d7e9499cd1.png)

This is your app when I launch it. I have alredy set the token.txt file and I have alredy installed ffmpeg.

**Comment by ravenkls** [comment]
Did you press the letter P on your keyboard? 
This isn't a fully working application at the moment so for now you have to press P to load the songs.

I'll add it to the readme as well, my bad.
